In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3,4,5,6])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.shape

(6,)

In [5]:
a1.dtype

dtype('int32')

In [6]:
a1.ndim

1

In [10]:
a2=np.array([[1,1,1,1,1],[2,2,2,2,2]])

In [11]:
a2.shape

(2, 5)

In [12]:
a2.ndim

2

In [13]:
a2.size

10

In [14]:
type(a2)

numpy.ndarray

In [15]:
a2.dtype

dtype('int32')

In [16]:
a3= np.array([[[3,3,3,3],[4,4,4,4]],[[5,5,5,5],[6,6,6,6]]])

In [17]:
a3

array([[[3, 3, 3, 3],
        [4, 4, 4, 4]],

       [[5, 5, 5, 5],
        [6, 6, 6, 6]]])

In [18]:
a3.ndim

3

In [19]:
a3.shape

(2, 2, 4)

In [20]:
a3.size

16

In [26]:
array1=np.ones(3)

In [27]:
array1

array([1., 1., 1.])

In [28]:
array2=np.ones((2,3))

In [29]:
array2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
array3=np.zeros((2,3))

In [31]:
array3

array([[0., 0., 0.],
       [0., 0., 0.]])